version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:0.118.5
    volumes:
      - /volume1/docker/homeassistant/config:/config
    environment:
      - TZ=America/New_York
    restart: always
    network_mode: host
    devices:
      - /dev/ttyACM1
  deconz:
    image: marthoc/deconz:stable
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /volume1/docker/homeassistant/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - TZ=America/New_York
      - DECONZ_WEB_PORT=8001
      - DECONZ_WS_PORT=8002
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
