
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#logger:
#  default: debug

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
tplink: !include tplink_devices.yaml
lutron_caseta_pro: !include lutron_caseta_pro.yaml
sensor: !include sensors.yaml
homekit: !include homekit.yaml
media_player:
  - platform: kodi
    host: !secret shield_ip
panel_iframe: !include panel_iframe.yaml
rest_command: !include sidetv.yaml
light:
  - platform: hyperion
    host: !secret hyperion_ip
  - platform: mqtt
    schema: template
    name: "Server Rack Lights"
    command_topic: "shellies/shellyrgbw2-6EEA1B/color/0/set"
    state_topic: "shellies/shellyrgbw2-6EEA1B/color/0/status"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    command_on_template: >
      {"turn": "on"
      {%- if brightness is defined -%}
      , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
      {%- endif -%}
      {%- if red is defined and green is defined and blue is defined -%}
      , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
      {%- endif -%}
      {%- if white_value is defined -%}
      , "white": {{ white_value }}
      {%- endif -%}
      {%- if effect is defined -%}
      , "effect": {{ effect }}
      {%- endif -%}
      }
    command_off_template: '{"turn":"off"}'
    state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
    brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
    red_template: '{{ value_json.red }}'
    green_template: '{{ value_json.green }}'
    blue_template: '{{ value_json.blue }}'
    white_value_template: '{{ value_json.white }}'
    effect_template: '{{ value_json.effect }}'
    qos: 2
device_tracker:
  - platform: mqtt
    devices:
      jason_watch: !secret jason_watch_presence_topic
    payload_home: 'true'
    payload_not_home: 'false'
    source_type: bluetooth
