- platform: template
  sensors:
    basementharmonyhubstatus:
      value_template: '{{ state_attr("remote.basement", "current_activity") }}'
      friendly_name: 'Basement Harmony Status'
    last_alexa:
      value_template: >-
        {{ expand(states.group.echos) | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
